post_install() {
  for conf_file in /etc/openvpn/*; do
    if [ -f $conf_file ]; then
      printf "\n# This updates the resolvconf with dns settings\nscript-security 2\nup /usr/bin/update-resolv-conf.sh\ndown /usr/bin/update-resolv-conf.sh" >> $conf_file
    fi
  done
}

post_remove() {
  for conf_file in /etc/openvpn/*; do
    if [ -f $conf_file ]; then
      head -n -5 > $conf_file
    fi
  done
}
